name: Deploy from GitLab to GitHub Pages

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages

    - name: Fetch from GitLab
      run: |
        mkdir gitlab-project
        cd gitlab-project
        git init
        git remote add origin https://oauth2:${{ secrets.GITLAB_SECRET }}@code.ovgu.de/seidl/se24-exercise09.git
        git fetch origin
        git checkout develop
        mv ./gitlab-project/* ./
        git init

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.11.0

    - name: Install Angular CLI and dependencies
      working-directory: ./GameTracker
      run: |
        npm install -g @angular/cli
        npm ci
        ng add angular-cli-ghpages --skip-confirmation

    - name: Build project
      working-directory: ./GameTracker
      run: ng build --base-href https://d4purebacon.github.io/GameTracker-Wizard/

    - name: Deploy to GitHub Pages
      env:
        GIT_AUTHOR_NAME: GitHub Actions
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: actions@github.com
      run: |
        touch .nojekyll
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
