name: Deploy from GitLab to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - gh-pages
      - deploy-test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Fetch from GitLab
      run: |
        mkdir gitlab-project
        cd gitlab-project
        git init
        git remote add origin https://oauth2:${{ secrets.GITLAB_SECRET }}@code.ovgu.de/seidl/se24-exercise09.git
        git fetch origin
        git checkout develop

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.11.0

    - name: Install dependencies
      working-directory: gitlab-project/GameTracker
      run: npm install

    - name: Build project
      working-directory: gitlab-project/GameTracker
      run: npm run build --

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gitlab-project/GameTracker/dist
