name: Deploy from GitLab to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - gh-pages
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3

    - name: Fetch from GitLab
      run: |
        mkdir gitlab-project
        cd gitlab-project
        git init
        git remote add origin https://oauth2:${{ secrets.GITLAB_SECRET }}@code.ovgu.de/seidl/se24-exercise09.git
        git fetch origin
        git checkout develop

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.11.0

    - name: Install dependencies
      working-directory: gitlab-project/GameTracker
      run: npm install

    - name: Build project
      working-directory: gitlab-project/GameTracker
      run: npm run build --

    - name: Move built files to GitHub repository
      run: |
        mv gitlab-project/GameTracker/dist/* ./dist/
        cd

    - name: Add dist
      env:
        GIT_AUTHOR_NAME: GitHub Actions
        GIT_AUTHOR_EMAIL: actions@github.com
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: actions@github.com
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote update
        git fetch
        git checkout origin/gh-pages
        git add dist
        git commit -m "Deploy to GitHub Pages"
        git push origin HEAD:gh-pages
